version: "3"

services:
    import-to-db:
      build: "./import-to-db"
      volumes: 
        - ./import-to-db/main.py:/usr/src/app/main.py
      depends_on: 
        - mongo
    api:
      container_name: api
      build: "./api"
      ports:
        - 8080:3000
      volumes: 
        - ./api/src:/app/src
        - logs:/app/logs
      depends_on: 
        - mongo
        -  import-to-db
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:8080/-/healthy"]
        interval: 10s
        timeout: 10s
        retries: 5
      environment: 
        mongo_user: root
        mongo_pass: example
    prom:
    
      image: prom/prometheus
      # ports: 
      #     - 9090:9090
      depends_on: 
        - api
 
      volumes: 
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:9090/-/healthy"]
          interval: 10s
          timeout: 10s
          retries: 5
      network_mode: host
    es01:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
      container_name: es01
      labels: 
        - co.elastic.logs/enabled=false
                
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - xpack.security.http.ssl.enabled=false
        - xpack.security.transport.ssl.enabled=false

      ulimits:
        memlock:
          soft: "-1"
          hard: "-1"
      volumes:
        - data01:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
    fileb:
      user: root 
      labels: 
        - co.elastic.logs/enabled=false

      image: docker.elastic.co/beats/filebeat:7.13.3
      volumes: 
        - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
        - logs:/logs
      depends_on: 
        - es01
      command: ["filebeat",  "-e", "--strict.perms=false","run"]
      environment: 
        # - setup.kibana.host=kibana:5601
        - ELASTICSEARCH_HOSTS=http://es01:9200
        - xpack.security.enabled=false
        - output.elasticsearch.hosts=["es01:9200"]
    kibana:
        labels: 
            - co.elastic.logs/enabled=false

        image: docker.elastic.co/kibana/kibana:7.13.3
        depends_on: 
            - es01
        ports: 
          - 5601:5601
        volumes:
          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    grafana:
      image: grafana/grafana
      ports: 
        - 3000:3000
    mongo:
      image: mongo
      restart: always
      volumes: 
        - ./datadir:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
  
volumes:
    logs:
    
    data01:
        driver: local