filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true


filebeat.inputs:
- type: log
  paths:
    - /logs/*.log
  # include_lines: ['{']
  # exclude_lines: ['^DBG']
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
  # json.message_key: log.levelkc
  scan_frequency: 0.5
processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
